edition = "2021"
max_width = 100
hard_tabs = false
tab_spaces = 4
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
reorder_imports = true
use_small_heuristics = "Max"
fn_single_line = false
where_single_line = false
struct_lit_single_line = false
trailing_comma = "Vertical"
match_block_trailing_comma = true
normalize_comments = true
normalize_doc_attributes = true
wrap_comments = true
comment_width = 80
spaces_around_ranges = false
space_before_colon = false
space_after_colon = true
blank_lines_upper_bound = 2
blank_lines_lower_bound = 0
chain_width = 60
overflow_delimited_expr = true
format_macro_matchers = true
format_macro_bodies = true
format_strings = true
merge_derives = true
use_try_shorthand = true
use_field_init_shorthand = true
force_explicit_abi = true
newline_style = "Unix"
